### PR TITLE
Proxy MCP client name in local stdio server User-Agent

### LINKED ISSUE #250: proxy mcp client name in the local mcp stdio server
### Describe the bug

Look into making the local stdio MCP server (tools/modelcontextprotocol/src/index.ts) take in the mcp client name and proxying that thru the user agent

### To Reproduce

* connect with local mcp
* use cursor

### Expected behavior

* cursor's mcp client name should be sent to the http server local mcp is proxying to

### Code snippets

```Python

```

### OS

macOS

### Language version

npm

### Library version

stripe

### API version

n/a

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mvanhorn**
## Summary

Extracts the MCP client name from the `initialize` request and includes it in the `User-Agent` header sent to `mcp.stripe.com`. When Cursor connects, the header reads `stripe-mcp-local/0.3.1 (cursor)` instead of the static `stripe-mcp-local/0.3.1`.

## Changes

- **Deferred HTTP transport creation:** The HTTP transport is now created on the first stdio message instead of upfront. This lets us inspect the `initialize` message for `clientInfo.name` before building headers.
- **`extractClientName()`:** Parses a `JSONRPCMessage` and returns the client name if the message is an `initialize` request with `clientInfo`.
- **`buildUserAgent()`:** Appends the client name in parentheses to the base user agent string.
- **Tests:** 6 new test cases covering client name extraction (Cursor, Claude Desktop, missing clientInfo, non-initialize messages, responses, notifications) and User-Agent formatting.

All messages are still forwarded unchanged - the proxy only peeks at the first message for metadata.

## Testing

All CI checks pass locally:
- `pnpm run build` - clean
- `pnpm run lint` - clean
- `pnpm run prettier-check` - clean
- `pnpm run test` - 17/17 passing (6 new + 11 existing)

Fixes #250

This contribution was developed with AI assistance (Claude Code).

### CODE REVIEW

File: tools/modelcontextprotocol/src/index.ts [hunk 1]
```diff
@@ -2,56 +2,24 @@
...
-/**
- * Build the User-Agent string, appending the MCP client name if available.
- */
-export function buildUserAgent(clientName?: string): string {
-  if (clientName) {
-    return `${BASE_USER_AGENT} (${clientName})`;
-  }
-  return BASE_USER_AGENT;
-}
+export {extractClientName, buildUserAgent};
```
Comment (matv-stripe) [inline tools/modelcontextprotocol/src/index.ts]: do we need to reexport here?
